### PR TITLE
Refactor eigen solver

### PR DESCRIPTION
**Pull request by ftalbrecht**
* the eigenvectors are now returned as a matrix, not as a vector of vectors
* all options are now fixed in the ctors, not given in the functions (this allows for efficient all-at-once construction of decomposition)
* added lots of checks
* added tests

What we could do additionally is to disable all checks if `DXT_DISABLE_CHECKS` is defined. That way we can decouple check enabling/disabling from debug/release build...

@tobiasleibner If you have the time, please check if your code still works with the new design.

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Tested and confirmed that my code works fine with the new design, so for my part this can be merged.

**Comment by ftalbrecht** [comment]
We have a timeout for one builder, but the tests _should_ be fine.

**Comment by renemilk** [comment]
Binning isn't easy for this repo. It's now the first time that binaries/tests are actually missing in non-full builders, whereas in other repo there's just disabled tests in an otherwise active source file. My Cmake setup cannot handle this atm: https://travis-ci.org/dune-community/dune-xt-la/jobs/310085643

This will need some fixing on the builder_definition.cmake generator.

**Comment by renemilk** [comment]
So apparently checking for a test's existence does not work like it should as per the doc: https://cmake.org/cmake/help/v3.6/command/if.html
WIth https://github.com/dune-community/dune-xt-common/commit/2621d88d6c594564ae9ea2bd062c1b2024bd7f82 and in d553abd  I get 
```
CMake Error at dune/xt/la/test/builder_definitions.cmake:23 (if):
  if given arguments:

    "TEST" "test_container_CommonDenseMatrix_double_la_container_0002"

  Unknown arguments specified
Call Stack (most recent call first):
  dune/xt/la/test/CMakeLists.txt:22 (include)

```

Open for fixes.

**Comment by ftalbrecht** [comment]
If I understand you correctly it would help to not use the test disabling of test tools via the `.mini` files but rather always have all test binaries but replace the test within these manually? That is some work, but not too much, we could manage.

**Comment by renemilk** [comment]
Yes, that would help. One wouldn't do that manually though, but use the templating mechanism I've introduced in dune-gdt.
Or someone tells me how  I'm using cmake wrong

**Comment by renemilk** [comment]
Yes, that would help. One wouldn't do that manually though, but via the templating mechanism I've introduced in dune-gdt (via xt-common)

**Comment by renemilk** [comment]
I'm actually not sure how that would mesh with runtime variations with config files we're using here

**Comment by renemilk** [comment]
I'll maybe get started with the python stuff for this on my train ride tonight

**Pull request merged**
