### PR TITLE
dailywork-ftschindler

### PR DESCRIPTION
**Pull request by ftalbrecht**

### CODE REVIEW

**Comment by ftalbrecht** [comment]
What I did not like in the old setup was that `container.hh` pulled more or less everything. So even if you only neede the `Backends` enum, you included every header.
We could also put these enums somewhere else (this also holds for `SpaceType` in dune-gdt, which currently resides in `type_traits.hh`). Any suggestions for a header name?
One central place where all of these enums go, with the same name in every module, or just situation-dependent headers, such as `backends.hh` in this case?

**Comment by renemilk** [comment]
Ah, I thought in gdt they were in the spaces/interface.hh header actually. Since that isn't really so, moving to the same location as in gdt makes more sense, agreed. 
Separate header in each module I'd like too. How about we call it 'enums.hh', or something else generic, cause they won't all be backend-related (in the future) I guess.

**Comment by ftalbrecht** [comment]
*sigh*, you are right, of course

**Comment by tobiasleibner** [comment]
Looks like the changes here are already included in the new master PR, so closing this. Feel free to reopen of I am wrong.

**Pull request closed without merging**
