### PR TITLE
New-master

### PR DESCRIPTION
**Pull request by tobiasleibner**

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Any ideas about https://travis-ci.org/dune-community/dune-xt-la/jobs/449876125, @renefritze?

**Comment by tobiasleibner** [comment]
Todo: Fix resize behavior before merging.

**Comment by renefritze** [comment]
Travis ran out of memory generating coverage information.

**Comment by tobiasleibner** [comment]
Yep that's what I thought. But it happens reproducibly, so any ideas to why it is using that much memory?

**Comment by renefritze** [comment]
It's not new that it uses a lot of memory. It is new that it uses more memory than travis offers though. Why it needs so much in general? I have no idea.

**Pull request merged**
