### PR TITLE
Cleanup algorithms, eigensolver change, change CommonDenseMatrix backend

### PR DESCRIPTION
**Pull request by tobiasleibner**
Refactoring for the algorithms to work with all containers. Also adds tests. 

In addition, this pull request tries to avoid copying the options file in our eigensolvers, which can take the majority of computation time for small matrices and adds a switch to disable all checks.

Also removes the ``SparsityPatternDefault`` (moved to ``dune-xt-common``).

### CODE REVIEW

**Comment by tobiasleibner** [comment]
Tests are passing locally, but of course depend on the changes in https://github.com/dune-community/dune-xt-common/pull/59, so they will fail here.

**Comment by ftalbrecht** [comment]
We decided to postpone a merge until we figured out the relations with the containers from dune-xt-common.

**Comment by tobiasleibner** [comment]
I undid the ``SparsityPatternDefault`` removal (see https://github.com/dune-community/dune-xt-common/pull/59). 
This pull request now also includes a change of the ``CommonDenseMatrix`` backend to a contiguous layout to be able to pass this matrix e.g. to routines from LAPACK. 
With the changes from  https://github.com/dune-community/dune-xt-common/pull/59, the tests are passing locally.

**Comment by tobiasleibner** [comment]
This now includes #42 and tests are passing except for #41.

**Comment by tobiasleibner** [comment]
I merged the ``python_infrastructure_update`` branch in this branch to help @TiKeil with getting the fixes for #41 to pass the tests.

**Comment by tobiasleibner** [comment]
Included in #44.

**Pull request closed without merging**
